<?php

namespace App\Services\HR;

use App\Constants\UserType;
use App\Models\User;
use App\Models\EmployeeWarning;
use App\Models\UserNotification;
use App\Events\UserNotificationEvent;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Exception;

class MarketerPerformanceService
{
    /**
     * Get marketer performance table.
     */
    public function getPerformanceTable(array $filters = []): LengthAwarePaginator
    {
        $year = $filters['year'] ?? now()->year;
        $month = $filters['month'] ?? now()->month;
        $perPage = $filters['per_page'] ?? 15;

        $query = User::active()
            ->marketers()
            ->with(['team', 'warnings']);

        // Filter by team
        if (!empty($filters['team_id'])) {
            $query->where('team_id', $filters['team_id']);
        }

        // Search by name
        if (!empty($filters['search'])) {
            $query->where('name', 'like', '%' . $filters['search'] . '%');
        }

        $marketers = $query->paginate($perPage);

        // Transform with performance data
        $marketers->getCollection()->transform(function ($marketer) use ($year, $month) {
            $marketer->target_achievement_rate = $marketer->getTargetAchievementRate($year, $month);
            $marketer->deposits_count = $marketer->getDepositsCount($year, $month);
            $marketer->warnings_count = $marketer->getWarningsCount($year);
            return $marketer;
        });

        return $marketers;
    }

    /**
     * Get single marketer performance details.
     */
    public function getMarketerPerformance(int $userId, ?int $year = null, ?int $month = null): array
    {
        $year = $year ?? now()->year;
        $month = $month ?? now()->month;

        $marketer = User::with(['team', 'warnings', 'salesTargetsAsMarketer'])
            ->findOrFail($userId);

        return [
            'user' => [
                'id' => $marketer->id,
                'name' => $marketer->name,
                'email' => $marketer->email,
                'phone' => $marketer->phone,
                'team' => $marketer->team ? [
                    'id' => $marketer->team->id,
                    'name' => $marketer->team->name,
                ] : null,
            ],
            'performance' => [
                'target_achievement_rate' => $marketer->getTargetAchievementRate($year, $month),
                'deposits_count' => $marketer->getDepositsCount($year, $month),
                'warnings_count' => $marketer->getWarningsCount($year),
            ],
            'targets' => $marketer->salesTargetsAsMarketer()
                ->whereYear('start_date', $year)
                ->get()
                ->map(fn($t) => [
                    'id' => $t->id,
                    'target_type' => $t->target_type,
                    'status' => $t->status,
                    'start_date' => $t->start_date,
                    'end_date' => $t->end_date,
                ]),
            'warnings' => $marketer->warnings()
                ->whereYear('warning_date', $year)
                ->orderBy('warning_date', 'desc')
                ->get(),
        ];
    }

    /**
     * Check all marketers and issue auto-warnings for poor performance.
     * Called by scheduled command.
     */
    public function checkAndIssueAutoWarnings(float $threshold = 50.0): int
    {
        $year = now()->year;
        $month = now()->month;
        $warningsIssued = 0;

        $marketers = User::active()->marketers()->get();

        foreach ($marketers as $marketer) {
            $achievementRate = $marketer->getTargetAchievementRate($year, $month);

            // Skip if achievement is above threshold
            if ($achievementRate >= $threshold) {
                continue;
            }

            // Check if auto-warning already issued this month
            $existingWarning = EmployeeWarning::forEmployee($marketer->id)
                ->autoGenerated()
                ->performance()
                ->inMonth($year, $month)
                ->exists();

            if ($existingWarning) {
                continue;
            }

            DB::beginTransaction();
            try {
                // Create auto-warning
                EmployeeWarning::create([
                    'user_id' => $marketer->id,
                    'issued_by' => null, // Auto-generated
                    'type' => 'performance',
                    'reason' => 'نسبة تحقيق الأهداف أقل من المطلوب',
                    'details' => sprintf(
                        'نسبة تحقيق الأهداف للشهر %d/%d: %.2f%% (المطلوب: %.2f%%)',
                        $month, $year, $achievementRate, $threshold
                    ),
                    'is_auto_generated' => true,
                    'warning_date' => now()->toDateString(),
                ]);

                DB::commit();
                $warningsIssued++;

                // Notify HR users
                $this->notifyHrAboutWarning($marketer, $achievementRate);

            } catch (Exception $e) {
                DB::rollBack();
                \Log::error("Failed to issue auto-warning for user {$marketer->id}: " . $e->getMessage());
            }
        }

        return $warningsIssued;
    }

    /**
     * Notify HR users about auto-generated warning.
     */
    protected function notifyHrAboutWarning(User $marketer, float $achievementRate): void
    {
        $hrUsers = User::whereIn('type', [UserType::HR, 'HR'])->get();

        $message = sprintf(
            'تحذير تلقائي: الموظف %s - نسبة تحقيق الأهداف %.2f%%',
            $marketer->name,
            $achievementRate
        );

        foreach ($hrUsers as $hrUser) {
            UserNotification::create([
                'user_id' => $hrUser->id,
                'message' => $message,
            ]);

            event(new UserNotificationEvent($hrUser->id, $message));
        }
    }
}
