<?php

namespace App\Filament\Admin\Resources\ClaimFiles;

use App\Filament\Admin\Concerns\ChecksFilamentNavigationGroupGate;
use App\Filament\Admin\Concerns\HasGovernanceAuthorization;
use App\Filament\Admin\Resources\ClaimFiles\Pages\ListClaimFiles;
use App\Filament\Admin\Resources\ClaimFiles\Pages\ViewClaimFile;
use App\Models\ClaimFile;
use App\Models\User;
use App\Services\Credit\ClaimFileService;
use App\Services\Governance\GovernanceAuditLogger;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Actions\ViewAction;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\KeyValueEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class ClaimFileResource extends Resource
{
    use ChecksFilamentNavigationGroupGate;
    use HasGovernanceAuthorization;

    protected static ?string $model = ClaimFile::class;

    protected static ?string $slug = 'claim-files';

    protected static string | \BackedEnum | null $navigationIcon = Heroicon::OutlinedFolder;

    protected static ?string $navigationLabel = 'Claim File Review';

    protected static string | \UnitEnum | null $navigationGroup = 'Credit Oversight';

    protected static ?int $navigationSort = 30;

    /** @internal Overridden by AccountingClaimFileResource for Accounting & Finance navigation. */
    protected static function governanceGroupForClaimFiles(): string
    {
        return 'Credit Oversight';
    }

    /** @internal Overridden by AccountingClaimFileResource. */
    protected static function claimFilesViewPermission(): string
    {
        return 'credit.claim_files.view';
    }

    /** @internal Overridden by AccountingClaimFileResource. */
    protected static function claimFilesManagePermission(): string
    {
        return 'credit.claim_files.manage';
    }

    /** @internal Overridden by AccountingClaimFileResource. */
    protected static function claimFilePdfGeneratedAuditEvent(): string
    {
        return 'governance.credit.claim_file.pdf_generated';
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query): Builder => $query->with(['reservation.contract', 'reservation.contractUnit', 'reservations', 'generatedBy'])->latest())
            ->columns([
                TextColumn::make('id')->sortable(),
                IconColumn::make('is_combined')->label('Combined')->boolean(),
                TextColumn::make('project_name')
                    ->label('Project')
                    ->state(fn (ClaimFile $record): string => $record->getProjectName() ?? $record->reservation?->contract?->project_name ?? '-'),
                TextColumn::make('reservation_reference')
                    ->label('Booking Reference')
                    ->state(fn (ClaimFile $record): string => $record->isCombined() ? ((string) $record->reservations()->count() . ' reservations') : ('#' . ($record->sales_reservation_id ?? '-'))),
                TextColumn::make('total_claim_amount')->label('Claim Amount')->money('AED')->placeholder('-'),
                TextColumn::make('generatedBy.name')->label('Generated By')->placeholder('-'),
                IconColumn::make('has_pdf')
                    ->label('PDF')
                    ->boolean()
                    ->state(fn (ClaimFile $record): bool => $record->hasPdf()),
                TextColumn::make('created_at')->dateTime(),
            ])
            ->filters([
                TernaryFilter::make('is_combined')
                    ->label('Combined Claim'),
                Filter::make('created_range')
                    ->form([
                        \Filament\Forms\Components\DatePicker::make('from')
                            ->label('From'),
                        \Filament\Forms\Components\DatePicker::make('until')
                            ->label('Until'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when($data['from'] ?? null, fn (Builder $q, string $date) => $q->whereDate('created_at', '>=', $date))
                            ->when($data['until'] ?? null, fn (Builder $q, string $date) => $q->whereDate('created_at', '<=', $date));
                    }),
            ])
            ->actions([
                ViewAction::make(),
                Action::make('generatePdf')
                    ->label('Generate PDF')
                    ->icon(Heroicon::OutlinedDocumentArrowDown)
                    ->visible(fn (ClaimFile $record): bool => static::canGovernanceMutation(static::claimFilesManagePermission()) && ! $record->hasPdf())
                    ->action(function (ClaimFile $record): void {
                        $actor = auth()->user();

                        abort_unless($actor instanceof User, 403);

                        $beforePdf = $record->pdf_path;

                        $path = app(ClaimFileService::class)->generatePdf($record->id);

                        $record->refresh();

                        app(GovernanceAuditLogger::class)->log(static::claimFilePdfGeneratedAuditEvent(), $record, [
                            'before' => ['pdf_path' => $beforePdf],
                            'after' => ['pdf_path' => $record->pdf_path, 'storage_path' => $path],
                        ], $actor);

                        Notification::make()
                            ->success()
                            ->title('Claim file PDF generated.')
                            ->send();
                    }),
            ]);
    }

    public static function infolist(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Claim File Review')
                ->schema([
                    TextEntry::make('id'),
                    IconEntry::make('is_combined')->label('Combined')->boolean(),
                    TextEntry::make('claim_type')->placeholder('-'),
                    TextEntry::make('total_claim_amount')->label('Claim Amount')->money('AED')->placeholder('-'),
                    TextEntry::make('generatedBy.name')->label('Generated By')->placeholder('-'),
                    IconEntry::make('has_pdf')->label('PDF Generated')->state(fn (ClaimFile $record): bool => $record->hasPdf())->boolean(),
                    TextEntry::make('notes')->placeholder('-')->columnSpanFull(),
                ])
                ->columns(2),
            Section::make('Reservation')
                ->schema([
                    TextEntry::make('reservation.id')->label('Primary Booking')->placeholder('-'),
                    TextEntry::make('reservation.contract.project_name')->label('Project')->placeholder('-'),
                    TextEntry::make('reservation.contractUnit.unit_number')->label('Unit')->placeholder('-'),
                    TextEntry::make('reservation.client_name')->label('Client')->placeholder('-'),
                    TextEntry::make('reservation.credit_status')->label('Credit Status')->badge()->placeholder('-'),
                    TextEntry::make('combined_count')
                        ->label('Combined Reservations')
                        ->state(fn (ClaimFile $record): string => (string) $record->reservations()->count()),
                ])
                ->columns(2),
            Section::make('Snapshot')
                ->schema([
                    KeyValueEntry::make('file_data')
                        ->state(fn (ClaimFile $record): array => static::snapshotState($record))
                        ->columnSpanFull(),
                ]),
        ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListClaimFiles::route('/'),
            'view' => ViewClaimFile::route('/{record}'),
        ];
    }

    public static function canViewAny(): bool
    {
        return static::canAccessGovernancePage(static::governanceGroupForClaimFiles(), static::claimFilesViewPermission());
    }

    public static function canView(Model $record): bool
    {
        return static::canAccessGovernancePage(static::governanceGroupForClaimFiles(), static::claimFilesViewPermission());
    }

    public static function canCreate(): bool
    {
        return static::canGovernanceMutation(static::claimFilesManagePermission());
    }

    public static function canEdit(Model $record): bool
    {
        return false;
    }

    public static function canDelete(Model $record): bool
    {
        return false;
    }

    public static function canDeleteAny(): bool
    {
        return false;
    }

    public static function canForceDelete(Model $record): bool
    {
        return false;
    }

    public static function canRestore(Model $record): bool
    {
        return false;
    }

    protected static function snapshotState(ClaimFile $record): array
    {
        return collect($record->file_data ?? [])
            ->mapWithKeys(function (mixed $value, string $key): array {
                if (is_array($value)) {
                    return [$key => json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?: '[]'];
                }

                return [$key => $value === null || $value === '' ? '-' : (string) $value];
            })
            ->all();
    }
}
