<?php

namespace Database\Seeders;

use App\Models\EmployeeContract;
use App\Models\EmployeeWarning;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class HRSeeder extends Seeder
{
    public function run(): void
    {
        $counts = SeedCounts::all();
        $nonAdminUsers = User::where('type', '!=', 'admin')->get();

        foreach ($nonAdminUsers as $index => $user) {
            $status = $index % 3 === 0 ? 'draft' : ($index % 5 === 0 ? 'expired' : 'active');
            EmployeeContract::firstOrCreate(
                ['user_id' => $user->id],
                ['status' => $status]
            );
        }

        $hrUsers = User::where('type', 'hr')->pluck('id')->all();
        $hrPool = $hrUsers ?: User::where('type', 'admin')->pluck('id')->all();

        for ($i = 0; $i < $counts['employee_warnings']; $i++) {
            $auto = $i % 5 === 0;
            $factory = EmployeeWarning::factory();
            if ($auto) {
                $factory = $factory->autoGenerated();
            }
            $factory->create([
                'user_id' => $nonAdminUsers->random()->id,
                'issued_by' => $auto ? null : Arr::random($hrPool),
            ]);
        }
    }
}
