<?php

namespace Database\Seeders;

use App\Models\EmployeeContract;
use App\Models\EmployeeWarning;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class HRSeeder extends Seeder
{
    protected array $jobTitles = [
        'مدير مبيعات',
        'مسوق عقاري',
        'موظف موارد بشرية',
        'محاسب',
        'موظف ائتمان',
        'مدير مشاريع',
        'محرر فيديو',
        'مطور أنظمة',
    ];

    protected array $departments = [
        'المبيعات',
        'التسويق',
        'الموارد البشرية',
        'المحاسبة',
        'الائتمان',
        'إدارة المشاريع',
        'المونتاج',
        'التطوير',
    ];

    protected array $workTypes = ['full_time', 'part_time', 'contract'];

    public function run(): void
    {
        $counts = SeedCounts::all();
        $nonAdminUsers = User::where('type', '!=', 'admin')->get();

        foreach ($nonAdminUsers as $index => $user) {
            $contractStatuses = ['draft', 'active', 'expired', 'terminated'];
            $status = $contractStatuses[$index % 4];
            $startDate = now()->subDays(fake()->numberBetween(0, 365))->toDateString();

            $endDate = $startDate;
            if ($status === 'active') {
                $endDate = now()->addDays(fake()->numberBetween(30, 365 * 2))->toDateString();
            } elseif (in_array($status, ['expired', 'terminated'])) {
                $endDate = now()->subDays(fake()->numberBetween(1, 365))->toDateString();
            }

            $deptIndex = $index % count($this->departments);
            EmployeeContract::firstOrCreate(
                ['user_id' => $user->id],
                [
                    'status' => $status,
                    'start_date' => $startDate,
                    'end_date' => $endDate,
                    'contract_data' => [
                        'job_title' => $this->jobTitles[$deptIndex % count($this->jobTitles)],
                        'department' => $this->departments[$deptIndex],
                        'salary' => fake()->numberBetween(3000, 20000),
                        'work_type' => Arr::random($this->workTypes),
                        'probation_period' => '90 يوم',
                        'terms' => 'يلتزم الموظف ببنود العقد وأخلاقيات العمل. مدة التجربة 90 يوماً قابلة للتمديد وفق السياسة المعتمدة.',
                        'benefits' => 'تأمين طبي، إجازة سنوية 21 يوماً، تذاكر سفر سنوية حسب السياسة.',
                    ],
                ]
            );
        }

        $hrUsers = User::where('type', 'hr')->pluck('id')->all();
        $hrPool = $hrUsers ?: User::where('type', 'admin')->pluck('id')->all();

        for ($i = 0; $i < $counts['employee_warnings']; $i++) {
            $auto = $i % 5 === 0;
            $factory = EmployeeWarning::factory();
            if ($auto) {
                $factory = $factory->autoGenerated();
            }
            $factory->create([
                'user_id' => $nonAdminUsers->random()->id,
                'issued_by' => $auto ? null : Arr::random($hrPool),
            ]);
        }
    }
}
