<?php

$salesBasePermissions = [
    'tasks.create',
    'sales.dashboard.view',
    'sales.projects.view',
    'sales.units.view',
    'sales.units.book',
    'sales.reservations.create',
    'sales.reservations.view',
    'sales.reservations.confirm',
    'sales.reservations.cancel',
    'sales.waiting_list.create',
    'sales.goals.view',
    'sales.schedule.view',
    'sales.targets.view',
    'sales.targets.update',
    'sales.attendance.view',
    'second_party.view',
    'notifications.view',
    'exclusive_projects.view',
    'exclusive_projects.request',
    'exclusive_projects.contract.complete',
    'exclusive_projects.contract.export',
    'use-ai-assistant',
];

$salesLeaderExtraPermissions = [
    'sales.waiting_list.convert',
    'sales.goals.create',
    'sales.team.manage',
    'sales.attendance.manage',
    'sales.tasks.manage',
    'sales.tasks.create_for_marketing',
    'sales.projects.allocate_shifts',
    'sales.negotiation.approve',
    'sales.payment-plan.manage',
    'ai-calls.manage',
];

return [
    'behavior_rules' => [
        'يُسمح بشرح سير العمل العام دون افتراض صلاحيات غير ممنوحة.',
        'لا تعرض بيانات أو خطوات تفيد بتنفيذ إجراءات محظورة أو غير مؤكدة للمستخدم.',
    ],
    'definitions' => [
        'contracts.view' => 'View own contracts and developers list (ContractPolicy).',
        'contracts.view_all' => 'View all contract lists and details.',
        'contracts.create' => 'Create new contracts.',
        'contracts.approve' => 'Approve or reject contracts.',
        'contracts.delete' => 'Delete contracts.',
        'units.view' => 'View contract units.',
        'units.edit' => 'Create or update contract units.',
        'units.csv_upload' => 'Upload CSV files for units.',
        'second_party.view' => 'View second party data.',
        'second_party.edit' => 'Edit second party data.',
        'departments.boards.view' => 'View boards department data.',
        'departments.boards.edit' => 'Edit boards department data.',
        'departments.photography.view' => 'View photography department data.',
        'departments.photography.edit' => 'Edit photography department data.',
        'departments.montage.view' => 'View montage department data.',
        'departments.montage.edit' => 'Edit montage department data.',
        'dashboard.analytics.view' => 'View dashboard analytics.',
        'notifications.view' => 'View notifications.',
        'notifications.manage' => 'Manage and send notifications.',
        'employees.manage' => 'Manage employees.',
        'admin.panel.access' => 'Access the centralized Filament governance panel.',
        'admin.dashboard.view' => 'View the governance home page and overview widgets.',
        'admin.users.view' => 'View governance user listings and user access summaries.',
        'admin.users.manage' => 'Create, update, activate, deactivate, delete, and restore users in governance.',
        'admin.roles.view' => 'View governance roles and their current permission memberships.',
        'admin.roles.manage' => 'Update role permission memberships inside governance.',
        'admin.permissions.view' => 'View the frozen permission dictionary and assignment awareness data.',
        'admin.permissions.manage' => 'Manage permission assignment workflows without creating new permissions.',
        'admin.direct_permissions.view' => 'View direct user permission assignments.',
        'admin.direct_permissions.manage' => 'Assign and revoke direct permissions for users.',
        'admin.effective_access.view' => 'Inspect effective access snapshots for governance users.',
        'admin.audit.view' => 'View governance audit history and mutation events.',
        'governance.oversight.workflow.view' => 'Read-only oversight of workflow tasks and notification queues in the governance panel.',
        'governance.approvals.center.view' => 'View the governance approvals center (cross-queue work snapshot).',
        'admin.temp_permissions.view' => 'View temporary permission grants in governance.',
        'admin.temp_permissions.manage' => 'Create and revoke time-bound direct permission grants in governance.',

        // Project Management
        'projects.view' => 'View projects and units.',
        'projects.create' => 'Create and enter project data.',
        'projects.media.upload' => 'Upload images and videos.',
        'projects.media.approve' => 'Approve images and videos (Manager only).',
        'projects.team.create' => 'Create project team.',
        'projects.team.assign_leader' => 'Assign team leader.',
        'projects.team.allocate' => 'Allocate team to project.',
        'projects.approve' => 'Approve projects (Manager only).',
        'projects.archive' => 'Archive projects (Manager only).',

        // Sales
        'sales.dashboard.view' => 'View sales dashboard.',
        'sales.projects.view' => 'View sales projects.',
        'sales.units.view' => 'View project units.',
        'sales.units.book' => 'Book available units.',
        'sales.reservations.create' => 'Create reservations.',
        'sales.reservations.view' => 'View reservations.',
        'sales.reservations.confirm' => 'Confirm reservations.',
        'sales.reservations.cancel' => 'Cancel reservations.',
        'sales.waiting_list.create' => 'Create waiting list booking.',
        'sales.waiting_list.convert' => 'Convert waiting to confirmed (Leader only).',
        'sales.goals.view' => 'View assigned goals.',
        'sales.goals.create' => 'Create goals for team (Leader only).',
        'sales.schedule.view' => 'View work schedule.',
        'sales.targets.view' => 'View targets.',
        'sales.targets.update' => 'Update target status.',
        'sales.team.manage' => 'Manage team (leader only).',
        'sales.attendance.view' => 'View attendance.',
        'sales.attendance.manage' => 'Manage team attendance.',
        'sales.tasks.manage' => 'Manage marketing tasks.',
        'sales.tasks.create_for_marketing' => 'Create daily tasks for marketing.',
        'sales.projects.allocate_shifts' => 'Allocate projects/shifts to marketing staff.',
        'sales.negotiation.approve' => 'Approve or reject negotiation requests.',
        'sales.payment-plan.manage' => 'Create and manage off-plan payment plans.',

        // Editing
        'editing.projects.view' => 'View projects and units.',
        'editing.media.upload' => 'Upload edited images and videos.',

        // HR
        'hr.dashboard.view' => 'View HR dashboard KPIs.',
        'hr.teams.view' => 'View teams and member counts in HR oversight.',
        'hr.teams.manage' => 'Manage teams (CRUD and member assignment).',
        'hr.employees.manage' => 'Full employee management.',
        'hr.users.view' => 'View employees list (for plans and team selection).',
        'hr.users.create' => 'Create new users with roles.',
        'hr.performance.view' => 'View team and employee performance.',
        'hr.warnings.view' => 'View employee warnings in HR oversight.',
        'hr.warnings.manage' => 'Issue and view employee warnings.',
        'hr.contracts.view' => 'View employee contracts in HR oversight.',
        'hr.contracts.manage' => 'Create and download employee contracts.',
        'hr.reports.view' => 'Access HR reports.',
        'hr.reports.print' => 'Print performance reports.',
        'tasks.create' => 'Create and manage tasks (إدارة المهام - إضافة مهمة، مهامي). System-wide: POST /api/tasks, GET /api/my-tasks, PATCH /api/my-tasks/{id}/status.',

        // Marketing
        'marketing.dashboard.view' => 'View marketing dashboard KPIs.',
        'marketing.projects.view' => 'View marketing projects and plans.',
        'marketing.plans.create' => 'Create marketing plans.',
        'marketing.budgets.manage' => 'Manage budgets and forecasts.',
        'marketing.tasks.view' => 'View marketing tasks and achievement rates.',
        'marketing.tasks.confirm' => 'Confirm daily task execution.',
        'marketing.reports.view' => 'View performance and budget reports.',
        'marketing.teams.view' => 'View marketing teams.',
        'marketing.teams.manage' => 'Manage marketing teams and assign campaigns.',
        'marketing.ads.view' => 'View ads accounts, campaigns, insights and outcomes (Marketing).',
        'marketing.ads.manage' => 'Sync ads and manage outcomes (Marketing).',

        // Exclusive Projects
        'exclusive_projects.view' => 'View exclusive project requests.',
        'exclusive_projects.request' => 'Request exclusive project (all except HR).',
        'exclusive_projects.approve' => 'Approve exclusive project requests (PM Manager only).',
        'exclusive_projects.contract.complete' => 'Complete contract after approval.',
        'exclusive_projects.contract.export' => 'Export contract copy.',

        // AI Assistant
        'use-ai-assistant' => 'Access the in-app AI help assistant.',
        'ai.knowledge.view' => 'View AI assistant knowledge base entries in governance oversight.',
        'manage-ai-knowledge' => 'Manage AI assistant knowledge base entries.',

        // AI Calling
        'ai.calls.view' => 'View AI interaction and audit logs in governance oversight.',
        'ai-calls.manage' => 'Manage AI calling system: initiate, view, retry calls and manage scripts.',

        // Credit
        'credit.dashboard.view' => 'View Credit department dashboard KPIs.',
        'credit.bookings.view' => 'View bookings in Credit department.',
        'credit.bookings.manage' => 'Cancel bookings, update client contact fields, log credit client contact, payment plan (Credit).',
        'credit.financing.view' => 'View financing details for a booking (Credit).',
        'credit.financing.manage' => 'Manage bank financing tracker stages.',
        'credit.title_transfer.manage' => 'Manage title transfer process.',
        'credit.claim_files.view' => 'View claim files list and details (Credit).',
        'credit.claim_files.manage' => 'Manage claim files: candidates, generate, PDF (Credit).',
        'credit.claim_files.generate' => 'Generate claim files.',
        'credit.payment_plan.manage' => 'Create and manage payment plans for on-map bookings (Credit).',

        // Accounting
        'accounting.claim_files.view' => 'View claim file candidates and list (Accounting).',
        'accounting.claim_files.manage' => 'Manage claim files: candidates, generate, PDF (Accounting).',
        'accounting.dashboard.view' => 'View accounting dashboard metrics.',
        'accounting.notifications.view' => 'View accounting notifications.',
        'accounting.sold-units.view' => 'View sold units with commission information.',
        'accounting.sold-units.manage' => 'Manage sold units and commissions.',
        'accounting.commissions.approve' => 'Approve or reject commission distributions.',
        'accounting.commissions.create' => 'Create manual commissions.',
        'accounting.deposits.view' => 'View deposit information.',
        'accounting.deposits.manage' => 'Manage deposits (confirm, refund).',
        'accounting.salaries.view' => 'View employee salaries and commissions.',
        'accounting.salaries.distribute' => 'Create and manage salary distributions.',
        'accounting.down_payment.confirm' => 'Confirm down payments.',

        // Commission & Deposit (CommissionRolesSeeder - also in definitions for admin sync)
        'commissions.view' => 'View commissions.',
        'commissions.create' => 'Create commissions.',
        'commissions.update' => 'Update commissions.',
        'commissions.delete' => 'Delete commissions.',
        'commissions.approve' => 'Approve commissions.',
        'commissions.mark_paid' => 'Mark commission as paid.',
        'commission_distributions.approve' => 'Approve commission distributions.',
        'commission_distributions.reject' => 'Reject commission distributions.',
        'deposits.view' => 'View deposits.',
        'deposits.create' => 'Create deposits.',
        'deposits.update' => 'Update deposits.',
        'deposits.delete' => 'Delete deposits.',
        'deposits.confirm_receipt' => 'Confirm deposit receipt.',
        'deposits.refund' => 'Refund deposit.',
    ],
    // Bootstrap role map - ONLY for migration/seeding, NOT a runtime dependency
    // In production, use DB permissions (Spatie or custom) as the source of truth
    // NOTE: RolesAndPermissionsSeeder overwrites admin with ALL permissions from definitions (array_keys).
    // AppServiceProvider Gate::before only bypasses non-governance abilities for the legacy admin role.
    'bootstrap_role_map' => [
        'admin' => [
            // Admin gets ALL permissions - seeder overwrites with array_keys($definitions)
            'contracts.view',
            'contracts.view_all',
            'contracts.create',
            'contracts.approve',
            'contracts.delete',
            'units.view',
            'units.edit',
            'units.csv_upload',
            'second_party.view',
            'second_party.edit',
            'departments.boards.view',
            'departments.boards.edit',
            'departments.photography.view',
            'departments.photography.edit',
            'departments.montage.view',
            'departments.montage.edit',
            'dashboard.analytics.view',
            'notifications.view',
            'notifications.manage',
            'employees.manage',
            'projects.view',
            'projects.create',
            'projects.media.upload',
            'projects.media.approve',
            'projects.team.create',
            'projects.team.assign_leader',
            'projects.team.allocate',
            'projects.approve',
            'projects.archive',
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.units.view',
            'sales.units.book',
            'sales.reservations.create',
            'sales.reservations.view',
            'sales.reservations.confirm',
            'sales.reservations.cancel',
            'sales.waiting_list.create',
            'sales.waiting_list.convert',
            'sales.goals.view',
            'sales.goals.create',
            'sales.schedule.view',
            'sales.targets.view',
            'sales.targets.update',
            'sales.team.manage',
            'sales.attendance.view',
            'sales.attendance.manage',
            'sales.tasks.manage',
            'sales.tasks.create_for_marketing',
            'sales.projects.allocate_shifts',
            'sales.negotiation.approve',
            'sales.payment-plan.manage',
            'editing.projects.view',
            'editing.media.upload',
            'hr.dashboard.view',
            'hr.teams.manage',
            'hr.employees.manage',
            'hr.users.create',
            'hr.performance.view',
            'hr.warnings.manage',
            'hr.contracts.manage',
            'hr.reports.view',
            'hr.reports.print',
            'marketing.dashboard.view',
            'marketing.projects.view',
            'marketing.plans.create',
            'marketing.budgets.manage',
            'marketing.tasks.view',
            'marketing.tasks.confirm',
            'marketing.reports.view',
            'marketing.teams.view',
            'marketing.teams.manage',
            'marketing.ads.view',
            'marketing.ads.manage',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.approve',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'credit.dashboard.view',
            'credit.bookings.view',
            'credit.financing.view',
            'credit.financing.manage',
            'credit.title_transfer.manage',
            'credit.claim_files.view',
            'credit.claim_files.manage',
            'credit.claim_files.generate',
            'credit.payment_plan.manage',
            'accounting.dashboard.view',
            'accounting.claim_files.view',
            'accounting.claim_files.manage',
            'accounting.notifications.view',
            'accounting.sold-units.view',
            'accounting.sold-units.manage',
            'accounting.commissions.approve',
            'accounting.commissions.create',
            'accounting.deposits.view',
            'accounting.deposits.manage',
            'accounting.salaries.view',
            'accounting.salaries.distribute',
            'accounting.down_payment.confirm',
            'use-ai-assistant',
            'manage-ai-knowledge',
            'tasks.create',
            'ai-calls.manage',
        ],
        'project_management' => [
            // Staff permissions (base)
            'contracts.view',
            'contracts.view_all',
            'contracts.approve',
            'units.view',
            'units.edit',
            'units.csv_upload',
            'second_party.view',
            'second_party.edit',
            'departments.boards.view',
            'departments.boards.edit',
            'departments.photography.view',
            'departments.photography.edit',
            'dashboard.analytics.view',
            'notifications.view',
            'projects.view',
            'projects.create',
            'projects.media.upload',
            'projects.team.create',
            'projects.team.assign_leader',
            'projects.team.allocate',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'sales.reservations.create',
            'use-ai-assistant',
            'tasks.create',
            // Manager permissions added dynamically when is_manager=true
        ],
        'editor' => [
            'contracts.view',
            'contracts.view_all',
            'departments.montage.view',
            'departments.montage.edit',
            'departments.boards.view',
            'departments.boards.edit',
            'departments.photography.view',
            'departments.photography.edit',
            'notifications.view',
            'editing.projects.view',
            'editing.media.upload',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
            'second_party.view',
        ],
        'developer' => [
            'contracts.view',
            'contracts.view_all',
            'contracts.create',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'marketing' => [
           'contracts.view_all',
            'marketing.dashboard.view',
            'marketing.projects.view',
            'marketing.plans.create',
            'marketing.budgets.manage',
            'marketing.tasks.view',
            'marketing.tasks.confirm',
            'marketing.reports.view',
            'marketing.teams.view',
            'marketing.teams.manage',
            'marketing.ads.view',
            'marketing.ads.manage',
            'hr.users.view',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'sales' => $salesBasePermissions,
        'sales_leader' => array_values(array_unique(array_merge(
            $salesBasePermissions,
            $salesLeaderExtraPermissions
        ))),
        'hr' => [
            'hr.dashboard.view',
            'hr.teams.manage',
            'hr.employees.manage',
            'hr.users.create',
            'hr.performance.view',
            'hr.warnings.manage',
            'hr.contracts.manage',
            'hr.reports.view',
            'hr.reports.print',
            'notifications.view',
            'use-ai-assistant',
            'tasks.create',
            // NO exclusive project permissions
        ],
        'credit' => [
            'contracts.view',
            'contracts.view_all',
            'credit.dashboard.view',
            'credit.bookings.view',
            'credit.bookings.manage',
            'credit.financing.view',
            'credit.financing.manage',
            'credit.title_transfer.manage',
            'credit.claim_files.view',
            'credit.claim_files.manage',
            'credit.payment_plan.manage',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'accounting' => [
            'contracts.view',
            'contracts.view_all',
            'accounting.dashboard.view',
            'accounting.claim_files.view',
            'accounting.claim_files.manage',
            'accounting.notifications.view',
            'accounting.sold-units.view',
            'accounting.sold-units.manage',
            'accounting.commissions.approve',
            'accounting.commissions.create',
            'accounting.deposits.view',
            'accounting.deposits.manage',
            'accounting.salaries.view',
            'accounting.salaries.distribute',
            'accounting.down_payment.confirm',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'inventory' => [
            // Needed for /api/inventory/* routes we added
            'contracts.view',
            'contracts.view_all',
            'units.view',
            'second_party.view',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'default' => [
            'contracts.view',
            'contracts.view_all',
            'notifications.view',
            'use-ai-assistant',
            'tasks.create',
        ],
        'accountant' => [
            'contracts.view',
            'contracts.view_all',
            'accounting.dashboard.view',
            'accounting.claim_files.view',
            'accounting.claim_files.manage',
            'accounting.notifications.view',
            'accounting.sold-units.view',
            'accounting.commissions.approve',
            'accounting.deposits.view',
            'accounting.deposits.manage',
            'accounting.salaries.view',
            'accounting.salaries.distribute',
            'notifications.view',
            'exclusive_projects.view',
            'exclusive_projects.request',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
            'use-ai-assistant',
            'tasks.create',
        ],
        'erp_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'admin.users.view',
            'admin.users.manage',
            'admin.roles.view',
            'admin.roles.manage',
            'admin.permissions.view',
            'admin.permissions.manage',
            'admin.direct_permissions.view',
            'admin.direct_permissions.manage',
            'admin.effective_access.view',
            'admin.audit.view',
            'admin.temp_permissions.view',
            'admin.temp_permissions.manage',
            'governance.oversight.workflow.view',
            'governance.approvals.center.view',
            'contracts.view_all',
            'units.view',
            'projects.view',
            'exclusive_projects.view',
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.reservations.view',
            'sales.targets.view',
            'sales.attendance.view',
            'hr.dashboard.view',
            'hr.teams.view',
            'hr.performance.view',
            'hr.warnings.view',
            'hr.contracts.view',
            'hr.reports.view',
            'marketing.dashboard.view',
            'marketing.projects.view',
            'marketing.tasks.view',
            'marketing.reports.view',
            'marketing.teams.view',
            'credit.dashboard.view',
            'credit.bookings.view',
            'credit.financing.view',
            'credit.claim_files.view',
            'accounting.dashboard.view',
            'accounting.notifications.view',
            'accounting.sold-units.view',
            'accounting.deposits.view',
            'accounting.salaries.view',
            'accounting.claim_files.view',
            'commissions.view',
            'ai.knowledge.view',
            'ai.calls.view',
            'notifications.view',
            'tasks.create',
        ],
        'super_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'admin.users.view',
            'admin.users.manage',
            'admin.roles.view',
            'admin.roles.manage',
            'admin.permissions.view',
            'admin.permissions.manage',
            'admin.direct_permissions.view',
            'admin.direct_permissions.manage',
            'admin.effective_access.view',
            'admin.audit.view',
            'admin.temp_permissions.view',
            'admin.temp_permissions.manage',
            'governance.oversight.workflow.view',
            'governance.approvals.center.view',
            'contracts.view_all',
            'units.view',
            'projects.view',
            'exclusive_projects.view',
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.reservations.view',
            'sales.targets.view',
            'sales.attendance.view',
            'hr.dashboard.view',
            'hr.teams.view',
            'hr.performance.view',
            'hr.warnings.view',
            'hr.contracts.view',
            'hr.reports.view',
            'marketing.dashboard.view',
            'marketing.projects.view',
            'marketing.tasks.view',
            'marketing.reports.view',
            'marketing.teams.view',
            'credit.dashboard.view',
            'credit.bookings.view',
            'credit.financing.view',
            'credit.claim_files.view',
            'credit.title_transfer.manage',
            'accounting.dashboard.view',
            'accounting.notifications.view',
            'accounting.sold-units.view',
            'accounting.deposits.view',
            'accounting.salaries.view',
            'accounting.claim_files.view',
            'commissions.view',
            'ai.knowledge.view',
            'ai.calls.view',
            'notifications.view',
            'tasks.create',
        ],
        'auditor_readonly' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'admin.users.view',
            'admin.roles.view',
            'admin.permissions.view',
            'admin.direct_permissions.view',
            'admin.effective_access.view',
            'admin.audit.view',
            'admin.temp_permissions.view',
        ],
        'credit_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'credit.dashboard.view',
            'notifications.manage',
            'credit.bookings.view',
            'credit.bookings.manage',
            'credit.financing.view',
            'credit.financing.manage',
            'credit.claim_files.view',
            'credit.claim_files.manage',
            'credit.claim_files.generate',
            'credit.title_transfer.manage',
        ],
        'projects_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'contracts.view_all',
            'contracts.approve',
            'units.view',
            'projects.view',
            'exclusive_projects.view',
            'exclusive_projects.approve',
            'exclusive_projects.contract.complete',
            'exclusive_projects.contract.export',
        ],
        'sales_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.reservations.view',
            'sales.reservations.confirm',
            'sales.reservations.cancel',
            'sales.targets.view',
            'sales.targets.update',
            'sales.attendance.view',
            'sales.attendance.manage',
        ],
        'hr_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'hr.dashboard.view',
            'hr.teams.view',
            'hr.teams.manage',
            'hr.performance.view',
            'hr.warnings.view',
            'hr.warnings.manage',
            'hr.contracts.view',
            'hr.contracts.manage',
            'hr.reports.view',
        ],
        'marketing_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'marketing.dashboard.view',
            'marketing.projects.view',
            'marketing.plans.create',
            'marketing.tasks.view',
            'marketing.tasks.confirm',
            'marketing.reports.view',
            'marketing.teams.view',
        ],
        'inventory_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'contracts.view_all',
            'units.view',
            'units.edit',
        ],
        'ai_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'ai.knowledge.view',
            'manage-ai-knowledge',
            'ai.calls.view',
        ],
        'workflow_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'governance.oversight.workflow.view',
            'governance.approvals.center.view',
            'notifications.view',
            'notifications.manage',
            'tasks.create',
        ],
        'accounting_admin' => [
            'admin.panel.access',
            'admin.dashboard.view',
            'accounting.dashboard.view',
            'accounting.notifications.view',
            'notifications.manage',
            'accounting.sold-units.view',
            'accounting.deposits.view',
            'accounting.deposits.manage',
            'accounting.down_payment.confirm',
            'accounting.commissions.approve',
            'accounting.salaries.view',
            'accounting.salaries.distribute',
            'accounting.claim_files.view',
            'accounting.claim_files.manage',
            'commissions.view',
            'commissions.mark_paid',
        ],
    ],
];
