<?php

return [
    'behavior_rules' => [
        'Always allowed to explain general workflows',
        'Never show data or steps that imply performing restricted actions',
    ],
    'definitions' => [
        'contracts.view' => 'View contract lists and details.',
        'contracts.view_all' => 'View all contracts across users.',
        'contracts.create' => 'Create new contracts.',
        'contracts.approve' => 'Approve or reject contracts.',
        'contracts.delete' => 'Delete contracts.',
        'units.view' => 'View contract units.',
        'units.edit' => 'Create or update contract units.',
        'units.csv_upload' => 'Upload CSV files for units.',
        'second_party.view' => 'View second party data.',
        'second_party.edit' => 'Edit second party data.',
        'departments.boards.view' => 'View boards department data.',
        'departments.boards.edit' => 'Edit boards department data.',
        'departments.photography.view' => 'View photography department data.',
        'departments.photography.edit' => 'Edit photography department data.',
        'departments.montage.view' => 'View montage department data.',
        'departments.montage.edit' => 'Edit montage department data.',
        'dashboard.analytics.view' => 'View dashboard analytics.',
        'notifications.view' => 'View notifications.',
        'notifications.manage' => 'Manage and send notifications.',
        'employees.manage' => 'Manage employees.',
        'sales.dashboard.view' => 'View sales dashboard.',
        'sales.projects.view' => 'View sales projects.',
        'sales.reservations.create' => 'Create reservations.',
        'sales.reservations.view' => 'View reservations.',
        'sales.reservations.confirm' => 'Confirm reservations.',
        'sales.reservations.cancel' => 'Cancel reservations.',
        'sales.targets.view' => 'View targets.',
        'sales.targets.update' => 'Update target status.',
        'sales.team.manage' => 'Manage team (leader only).',
        'sales.attendance.view' => 'View attendance.',
        'sales.attendance.manage' => 'Manage team attendance.',
        'sales.tasks.manage' => 'Manage marketing tasks.',
    ],
    // Bootstrap role map - ONLY for migration/seeding, NOT a runtime dependency
    // In production, use DB permissions (Spatie or custom) as the source of truth
    'bootstrap_role_map' => [
        'admin' => [
            'contracts.view',
            'contracts.view_all',
            'contracts.create',
            'contracts.approve',
            'units.view',
            'units.edit',
            'units.csv_upload',
            'second_party.view',
            'second_party.edit',
            'departments.boards.view',
            'departments.boards.edit',
            'departments.photography.view',
            'departments.photography.edit',
            'departments.montage.view',
            'departments.montage.edit',
            'dashboard.analytics.view',
            'notifications.view',
            'notifications.manage',
            'employees.manage',
        ],
        'project_management' => [
            'contracts.view',
            'contracts.view_all',
            'contracts.approve',
            'units.view',
            'units.edit',
            'units.csv_upload',
            'second_party.view',
            'second_party.edit',
            'departments.boards.view',
            'departments.boards.edit',
            'departments.photography.view',
            'departments.photography.edit',
            'dashboard.analytics.view',
            'notifications.view',
        ],
        'editor' => [
            'contracts.view',
            'contracts.view_all',
            'departments.montage.view',
            'departments.montage.edit',
            'notifications.view',
        ],
        'developer' => [
            'contracts.view',
            'contracts.create',
            'notifications.view',
        ],
        'sales' => [
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.reservations.create',
            'sales.reservations.view',
            'sales.reservations.confirm',
            'sales.reservations.cancel',
            'sales.targets.view',
            'sales.targets.update',
            'sales.attendance.view',
            'notifications.view',
        ],
        'sales_leader' => [
            'sales.dashboard.view',
            'sales.projects.view',
            'sales.reservations.view',
            'sales.targets.view',
            'sales.team.manage',
            'sales.attendance.manage',
            'sales.tasks.manage',
            'notifications.view',
        ],
        'default' => [
            'contracts.view',
            'notifications.view',
        ],
    ],
];
