<?php

namespace Database\Factories;

use App\Models\EmployeeWarning;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\EmployeeWarning>
 */
class EmployeeWarningFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = EmployeeWarning::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'issued_by' => User::factory(),
            'type' => fake()->randomElement(['performance', 'attendance', 'behavior', 'other']),
            'reason' => fake()->sentence(),
            'details' => fake()->paragraph(),
            'is_auto_generated' => false,
            'warning_date' => fake()->dateTimeBetween('-6 months', 'now')->format('Y-m-d'),
        ];
    }

    /**
     * Indicate that the warning is auto-generated.
     */
    public function autoGenerated(): static
    {
        return $this->state(fn(array $attributes) => [
            'is_auto_generated' => true,
            'issued_by' => null,
            'type' => 'performance',
        ]);
    }

    /**
     * Indicate that the warning is a performance warning.
     */
    public function performance(): static
    {
        return $this->state(fn(array $attributes) => [
            'type' => 'performance',
        ]);
    }

    /**
     * Indicate that the warning is an attendance warning.
     */
    public function attendance(): static
    {
        return $this->state(fn(array $attributes) => [
            'type' => 'attendance',
        ]);
    }
}

