<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Builder;

class EmployeeWarning extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'issued_by',
        'type',
        'reason',
        'details',
        'is_auto_generated',
        'warning_date',
    ];

    protected $casts = [
        'warning_date' => 'date',
        'is_auto_generated' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the employee who received this warning.
     */
    public function employee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * Get the user who issued this warning.
     */
    public function issuer(): BelongsTo
    {
        return $this->belongsTo(User::class, 'issued_by');
    }

    /**
     * Scope for performance warnings.
     */
    public function scopePerformance(Builder $query): Builder
    {
        return $query->where('type', 'performance');
    }

    /**
     * Scope for auto-generated warnings.
     */
    public function scopeAutoGenerated(Builder $query): Builder
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope for warnings in a specific month.
     */
    public function scopeInMonth(Builder $query, int $year, int $month): Builder
    {
        return $query->whereYear('warning_date', $year)
            ->whereMonth('warning_date', $month);
    }

    /**
     * Scope for warnings of a specific employee.
     */
    public function scopeForEmployee(Builder $query, int $userId): Builder
    {
        return $query->where('user_id', $userId);
    }

    /**
     * Check if this is a performance warning.
     */
    public function isPerformanceWarning(): bool
    {
        return $this->type === 'performance';
    }

    /**
     * Check if this is an auto-generated warning.
     */
    public function isAutoGenerated(): bool
    {
        return $this->is_auto_generated === true;
    }
}

